image:
  repository: teymurgahramanov/from-node-exporter
  pullPolicy: IfNotPresent
  tag: "" # Default is "{{ $.Chart.AppVersion }}"
config:
  exporter: {}
  targets: {}
serviceType: ClusterIP
labels: {}
# Common labels
annotations: {}
# Common annotations
daemonsetAnnotations: {}
podLabels: {}
podAnnotations: {}
configMapAnnotations: {}
serviceMapAnnotations: {}
nodeSelector: {}
affinity: {}
tolerations: []
resources: {}
volumes: {}
volumeMounts: {}