exporter:
  metricsListenPort: 8080
  metricsListenPath: /metrics
  defaultProbeInterval: 22
  defaultProbeTimeout: 10  
targets:
  - target1:
      address: api.example.com:8080
      module: tcp
      timeout: 15
  - target2:
      address: https://example.com
      module: http
      interval: 60