{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
{{- include "common.metadata" | nindent 2 }}
data:
{{- range $key, $subKey := .Values.configMap }}
  {{ $key }}: |-
{{ $subKey.data | indent 4 }}
{{- end }}
{{- end }}
