apiVersion: apps/v1
kind: Deployment
metadata:
{{- include "common.metadata" ( list $ "" ) | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        {{- include "common.labels" . | nindent 8 }}
      annotations:
    {{- if .Values.pod.annotations }}
      {{- toYaml .Values.podAnnotations | nindent 8 }}
    {{- end }}
    spec:
      containers:
      - name: your-container-name
        image: your-container-image:tag
        # Add additional container configuration as needed
        # For example, ports, volume mounts, etc.
spec:
  replicas: {{ .Values.pod.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}  
    {{- if .Values.pod.annotations }}
      {{- toYaml .Values.pod.annotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.app.name }}
      {{- end }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: default
              containerPort: {{ .Values.app.listenPort }}
          {{- if .Values.probes }}
            {{- toYaml .Values.probes | nindent 10 }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
         {{- if .Values.vault.secrets }}
          envFrom:
            {{- range $key, $subKey := .Values.vault.secrets }}
            - secretRef:
                name: {{ include "resource.name" ( list $ $key ) }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: time
              mountPath: /etc/localtime
          {{- if .Values.configMap }}
          {{- range $key, $subKey := .Values.configMap }}
            - name: configmap
              mountPath: {{ $subKey.mountPath }}
              subPath: {{ $key }}
          {{- end }}
          {{- end }}
          {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: time
          hostPath:
            path: /etc/localtime
       {{- if .Values.configMap }}
        - name: configmap
          configMap:
            name: {{ include "resource.name" ( list $ "" ) }}
      {{- end }}
      {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}